# Generated by Django 4.2.1 on 2023-05-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
