# Generated by Django 4.2.1 on 2023-05-25 13:08

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[accounts.validators.UnicodeUsernameValidator()]),
        ),
    ]
